export const DI_TOKENS = {
    CONTROLLERS: {
            BILLER_CONTROLLER: Symbol.for("BILLER_CONTROLLER"),
            BILL_CONTROLLER: Symbol.for("BILL_CONTROLLER"),
            PAYMENT_CONTROLLER: Symbol.for("PAYMENT_CONTROLLER"),
    },
    SERVICES: {
        BILLER_SERVICE: Symbol.for("BILLER_SERVICE"),
        PAYMENT_SERVICE: Symbol.for("PAYMENT_SERVICE"),
    },
    REPOSITORIES: {
        BILLER_REPOSITORY: Symbol.for("BILLER_REPOSITORY"),
        USERS_SAVED_BILLERS_REPOSITORY: Symbol.for("USERS_SAVED_BILLERS_REPOSITORY"),
        PAYMENT_REPOSITORY: Symbol.for("PAYMENT_REPOSITORY"),
        INVOICE_REPOSITORY: Symbol.for("INVOICE_REPOSITORY")
    },
    CLIENTS:{
        USER_SERVICE_CLIENT: Symbol.for("USER_SERVICE_CLIENT"),
        ACCOUNT_SERVICE_CLIENT: Symbol.for("ACCOUNT_SERVICE_CLIENT"),
       TRANSACTION_SERVICE_CLIENT:Symbol.for("TRANSACTION_SERVICE_CLIENT")
    
    }
} as const;
