export const DI_TOKENS = {
  CONTROLLERS: {
    REPORT_CONTROLLER: Symbol.for("REPORT_CONTROLLER"),
    ANALYTICS_CONTROLLER: Symbol.for("ANALYTICS_CONTROLLER"),
  },
  SERVICES: {
    REPORT_SERVICE: Symbol.for("REPORT_SERVICE"),
    ANALYTICS_SERVICE: Symbol.for("ANALYTICS_SERVICE"),
  },
  CLIENTS:{
    ACCOUNT_SERVICE_CLIENT: Symbol.for("ACCOUNT_SERVICE_CLIENT"),
    TRANSACTION_SERVICE_CLIENT: Symbol.for("TRANSACTION_SERVICE_CLIENT"),
    USER_SERVICE_CLIENT: Symbol.for("USER_SERVICE_CLIENT"),
  }
} as const;
