export enum TokenErrorCode {
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR",
  REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED",
}
